# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches:
      - master
      - staging
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  NAME: "vignesh sweekaran"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=vigneshsweekaran" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/staging')
        run: |
         echo "ENVIRONMENT=staging" >> $GITHUB_ENV
         echo "ECR_REPOSITORY=vigneshsweekaran-staging" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/dev')
        run: |
         echo "ENVIRONMENT=dev" >> $GITHUB_ENV
         echo "ECR_REPOSITORY=vigneshsweekaran-dev" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${GITHUB_REF##*/}
          echo $ENVIRONMENT
          echo $ECR_REPOSITORY
          echo $NAME
