name: Testing github actions inputs

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        type: choice
        description: Choose AWS Region
        required: true
        default: 'us-east-1'
        options: 
        - 'us-east-1'
        - 'us-east-2'
        - 'us-west-1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs on us-east-1
        if: ${{ github.event.inputs.AWS_REGION == 'us-east-1' }}
        run: |
          echo "${{ github.event.inputs.AWS_REGION }}"
          echo "Hello world"
