name: Testing github actions inputs

on:
  workflow_dispatch:
    inputs:
      name:
#         type: awsRegion
#         description: Choose AWS Region
#         options: 
#         - 'us-east-1'
#         - 'us-east-2'
#         - 'us-west-1'
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs on us-east-1
        if: ${{ github.event.inputs.awsRegion == 'us-east-1' }}
        run: |
          echo "${{ github.event.inputs.aws-region }}"
