name: Testing github actions services

on:
  workflow_dispatch:

jobs:
  test:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
