name: Testing github actions services

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running Job1"
  job2:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v2
      - run: |
         PGPASSWORD=postgres psql -h postgres -U postgres -d test -c 'select * from schema.table'
         
