name: Report Code Coverage

on:
  workflow_dispatch:
  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#       - name: Use Node.js 12.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x

#       - name: Install dependencies
#         run: npm ci

#       - name: Run tests
#         run: npm run test:coverage

      ## I need help around here, as test:coverage generates a file and I need to get a value from a file

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
