name: Report Code Coverage Test

on:
  pull_request:
#   workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#       - name: Use Node.js 12.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x

#       - name: Install dependencies
#         run: npm ci

#       - name: Run tests
#         run: npm run test:coverage

      ## I need help around here, as test:coverage generates a file and I need to get a value from a file

      - name: Read package.json
        id: coverage
        uses: juliangruber/read-file-action@v1
        with:
          path: ./coverage.txt
          
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ steps.coverage.outputs.content }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
